### ISSUE TITLE
Have vcf.iobio automatically detect which genome version your data is

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/vcf.iobio.io#41]
Have vcf.iobio automatically detect which genome version your data is - removing the need for the user to know and specify which version their data is.

**Comment by AlistairNWard** [comment]
Unfortunately this isn't always possible. There is no requirement to include information in the vcf that makes it clear which genome reference has been used.

**Comment by tonydisera** [comment]
For now, the VCF Filter values (e.g., PASS, ., etc) is populated based on the variants that have been analyzed across all loaded genes.  This isn't a complete solution, because variants with '.' filters won't be considered as 'FLAGGED FOR NOT MEETING FILTER CRITERIA' until a variant with a 'PASS' filter is encountered.  Take, for example the demo data.  When first loaded, variants for RAI1, which all have a filter of '.', are not flagged.

<img width="1088" alt="screen shot 2017-04-27 at 9 56 02 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513707/990407f8-2b94-11e7-9e0c-b653fc793081.png">

After gene PDGFB is selected, a variant with a 'PASS' filter is encountered.

<img width="946" alt="screen shot 2017-04-27 at 9 56 26 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513718/b89d7f90-2b94-11e7-91fe-320a20ba7c00.png">

Select RAI1 again.  Now its variants are flagged for not meeting filter criteria.
<img width="962" alt="screen shot 2017-04-27 at 9 56 37 pm" src="https://cloud.githubusercontent.com/assets/8420103/25513730/d4f71d68-2b94-11e7-9cba-0b4d07bdf1a6.png">

I think that the solution is to have a priori knowledge of all possible filter values used in the loaded VCF.
